---
- name: Install Forever
  npm: name=forever global=yes state=present
  sudo: yes

- name: Copy init script
  template: src=app_workers_init.conf.j2 dest=/etc/init/{{ app_process_name }}_workers.conf owner=root group=root
  sudo: yes